### ISSUE TITLE
[GENERAL] Permesso negato per scrivere in ./certs/

### ISSUE THREAD

**Issue by paolopoliti** [INPS-it/bugs.inps.it#27]
Quando faccio il dev setup su una VM Ubuntu 22.04, durante l'esecuzione di docker compose, il docker service 'certs' non riesce a scrivere nella directory ./certs/ in quanto la stessa ha owner root.

**Comment by peppelinux** [comment]
rimuovi la cartella o modifica i permessi prima dell'esecuzione, le azioni che finalizzi riportale nel compose così da non doverti ripetere

**Comment by paolopoliti** [comment]
Grazie della risposta @peppelinux. C'è una ragione precisa per cui si usa un bind mount invece che un volume?

**Comment by peppelinux** [comment]
no, cambia a tuo gusto

**Comment by paolopoliti** [comment]
Grazie @peppelinux . Scusa se ho eliminato il mio ultimo commento, pensavo di aver scritto una stupidaggine!
